#ifndef NVSHMEMI_TEAM_INTERNAL_H
#define NVSHMEMI_TEAM_INTERNAL_H

enum {
    NVSHMEM_TEAM_WORLD_INDEX = 0,
    NVSHMEM_TEAM_SHARED_INDEX,
    NVSHMEM_TEAM_NODE_INDEX,
    NVSHMEM_TEAM_SAME_GPU_INDEX,
    NVSHMEM_TEAM_GPU_LEADERS_INDEX,
    NVSHMEM_TEAMS_MIN
};

#define PSYNC_SIZE_PER_TEAM (2 * NVSHMEMI_SYNC_SIZE +                \
                             2 * NVSHMEMI_REDUCE_MIN_WRKDATA_SIZE)

#endif /* NVSHMEMI_TEAM_INTERNAL_H */
