# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
#
# See COPYRIGHT.txt for license information

"""
__init__.py for nvshmem Python package
"""
import os

__package_name__ = os.getenv("PACKAGE_NAME", "nvshmem4py")

# Version is autogenerated by setuptools_scm
from .version import version, __version__, __version_tuple__
